name: eztaox
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - arviz<=1.0.0
  - celerite
  - pip
  - pip:
      - eztaox @ git+https://github.com/LSST-AGN-Variability/EzTaoX.git